#! /bin/sh

if [[ $VENDOR != "apple" ]]
    then
    SHELL=$(readlink -f /proc/$$/exe | cut -d'/' -f3)
else
    SHELL=$(ps -p $$ | awk '$1 == PP {print $4}' PP=$$)
fi
if [[ $(which launch_universc.sh) != *"not found" ]]
    then
    SHELL='' 
    invocation=$0
else
    if [[ -z $ZSH_VERSION ]]
        then
        SHELL="zsh"
    elif [[ -z $KSH_VERSION ]]
       then
       SHELL="ksh"
    elif [[ -z $FISH_VERSION ]]
       then
       SHELL="fish"
    elif [[ -z $BASH_VERSION ]]
        then
        SHELL="bash"
    else
       SHELL=$SHELL
    fi
    invocation=$(echo $(basename $0))
fi

# add manual directory to PATH if not already found
## check config for Linux
if [[ -f /etc/manpath.config ]]
    then CONFIG="/etc/manpath.config"
    MANDIR=`grep "^MANDATORY_MANPATH" /etc/manpath.config | tail -n 1 | cut -f4`
fi
## check config for Mac
if [[ -f /etc/manpaths ]]
    then CONFIG="/etc/manpaths"
    MANDIR=`tail -n 1 ${CONFIG}`
fi
if [[ -z $CONFIG ]]
    then
    if [[ ! -z $MANPATH ]]
        then
        SHELL_RC=`echo ~/.${SHELL}rc`
        echo "export MANPATH=/usr/local/man" >> $SHELL_RC
        MANDIR=`echo ${MANPATH} | cut -d: -f1`
    fi
fi
#requires root priviledges
if [[ -w ${MANDIR} ]]
    then
    mkdir -p ${MANDIR}/man1
    cp man/launch_universc.sh man/launch_universc.sh.1
    mv man/launch_universc.sh.1 ${MANDIR}/man1/launch_universc.sh.1
    gzip ${MANDIR}/man1/launch_universc.sh.1
else
    echo "Directory ${MANDIR} not writeable"
    echo "Warning: installing manual requires root priviledges"
    echo "  Try running of the following:"
    echo "      sudo bash $( cd -P "$( dirname ${BASH_SOURCE[0]})" >/dev/null 2>&1 && pwd )/INSTALL"
    echo "      sudo make manual"
fi
