name: Docker container tests
on: workflow_dispach
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Run docker
        uses: addnab/docker-run-action@v1
        with:
          image: docker:latest
          run: echo "hello world"

  test-cellranger:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        registry: ${{ env.REGISTRY }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test
        push: false
    - name: Hello world 
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/cellranger_clean:latest echo "hello world"
    - name: Diagnostics
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/cellranger_clean:latest pwd;ls
    - name: Cell Ranger Call
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/cellranger_clean:latest cellranger count --help

  test-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: What OS is running
        run: uname -a
      - name: Where am i                
        run: pwd; ls
      - name: pull updates
        run: git pull --ff-only origin $(git branch --show-current)
      - name: call UniverSC
        run: ls launch_universc.sh 

  test-universc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: pull updates
      run: git pull --ff-only origin $(git branch --show-current)
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        registry: ${{ env.REGISTRY }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test
        push: false
    - name: Hello world
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test echo "hello world"
    - name: Diagnostics
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test pwd;ls
    - name: Cell Ranger Call
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test cellranger count --help
    - name: UniverSC Call
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test bash /universc/launch_universc.sh -v
    - name: Run test calls
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test bash /universc/test/test_call.sh
    - name: Git Status
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test git -C ./universc log --reverse | tail -n 10
    - name: Pull Updates
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test git -C ./universc pull --ff-only origin $(git branch --show-current)
    - name: Git Status  
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:test git -C ./universc log --reverse | tail -n 10
